(function(g){
'use strict';
const E=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const B=(text,fn,cls='')=>{const n=E('button',text,cls);n.type='button';n.onclick=()=>{try{fn();}catch(e){alert(e.message);}};return n;};
const own=(o,k)=>Object.prototype.hasOwnProperty.call(o,k),copy=x=>JSON.parse(JSON.stringify(x));
function box(parent,title,desc){const s=E('section',undefined,'lab-card ai-work-card');s.append(E('h3',title),E('p',desc,'muted'));parent.appendChild(s);return s;}
function field(parent,label,value,placeholder=''){const l=E('label',label),n=E('input');n.value=value;n.placeholder=placeholder;n.setAttribute('aria-label',label);l.appendChild(n);parent.appendChild(l);return n;}
function area(parent,label,placeholder=''){const l=E('label',label),n=E('textarea');n.placeholder=placeholder;n.setAttribute('aria-label',label);l.appendChild(n);parent.appendChild(l);return n;}
function strip(s){return String(s||'').trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');}
function selectText(a){a.focus();a.select();}
function modelNote(parent){const n=E('p','학생 기본: 5.6 Sol · Light. 같은 문제를 두 번 설명해도 해결되지 않을 때만 Sol · Medium. Sol이 없으면 Terra · Light 또는 계정 기본 모델을 사용하세요.','notice');parent.appendChild(n);}
function contentSpec(d){return {
 meta:{title:'게임 제목',tagline:'표지 소개',theme:'forest | amber | violet'},
 initialStats:Object.fromEntries(Object.keys(d.stats).filter(k=>!d.derivedStats?.some(r=>r.target===k)).map(k=>[k,d.stats[k]])),
 classes:(d.classes||[]).map(x=>({id:x.id,name:'새 이름',description:'새 설명',startingStats:x.startingStats||{}})),
 items:(d.items||[]).map(x=>({id:x.id,name:'새 이름',description:'실제 효과와 일치하는 설명',effect:x.effect||{}})),
 skills:(d.skills||[]).map(x=>({id:x.id,name:'새 이름'})),
 scenes:Object.entries(d.scenes).map(([id,s])=>({id,title:'새 제목',text:'2~4문장',choices:(s.choices||[]).map((c,i)=>({no:i+1,label:'새 선택 문구'}))}))
 };}
function contentPrompt(d,concept){const structure=contentSpec(d);return `나는 BRANCH 스토리 게임을 개인화한다. 코드는 만들지 말고 아래 형식의 JSON 객체 하나만 출력해라. 코드펜스와 설명문은 제외한다.\n\n내 기획\n- 장르/소재: ${concept.genre}\n- 배경: ${concept.setting}\n- 분위기: ${concept.mood}\n- 플레이어 목표: ${concept.goal}\n- 꼭 넣을 단어: ${concept.words}\n\n중요 규칙\n1. id와 장면 수, 선택지 수는 절대 바꾸지 않는다. 새 id를 만들거나 삭제하지 않는다.\n2. 장면 연결, 조건, 효과 대상은 에디터가 보존한다. 선택 문구는 실제 행동·비용·획득과 모순되지 않게 쓴다.\n3. initialStats와 startingStats는 현재 스탯 이름만 사용하고 0~100 정수로 쓴다.\n4. 아이템 effect는 현재 스탯 하나만 사용하고 -20~20 정수로 쓴다. 계산 스탯을 직접 바꾸지 않는다.\n5. 같은 세계관으로 통일하고 청소년 수업에 적합하게 쓴다.\n6. 실제 턴 교대, 장착·사용 버튼, 멀티플레이처럼 현재 엔진에 없는 기능을 설명하지 않는다.\n\n반드시 채울 구조\n${JSON.stringify(structure,null,2)}`;}
function validateContent(d,p){const errors=[],warn=[];if(!p||typeof p!=='object'||Array.isArray(p))return {errors:['JSON 객체가 필요합니다.'],warn};
 if(!p.meta||typeof p.meta.title!=='string'||!p.meta.title.trim())errors.push('meta.title이 필요합니다.');
 if(p.meta&&!['forest','amber','violet'].includes(p.meta.theme))errors.push('theme은 forest, amber, violet 중 하나입니다.');
 const derived=new Set((d.derivedStats||[]).map(r=>r.target)),stats=new Set(Object.keys(d.stats));
 if(!p.initialStats||typeof p.initialStats!=='object')errors.push('initialStats가 필요합니다.');else Object.entries(p.initialStats).forEach(([k,v])=>{if(!stats.has(k)||derived.has(k))errors.push('시작값에 허용되지 않는 스탯: '+k);if(!Number.isInteger(v)||v<0||v>100)errors.push('시작값 '+k+'은 0~100 정수여야 합니다.');});
 const checkPool=(key,current,check)=>{if(!Array.isArray(p[key])){errors.push(key+' 배열이 필요합니다.');return;}const want=new Set(current.map(x=>x.id)),got=new Set(p[key].map(x=>x?.id));for(const id of want)if(!got.has(id))errors.push(key+'에 '+id+'가 없습니다.');for(const id of got)if(!want.has(id))errors.push(key+'에 새 ID '+id+'를 사용할 수 없습니다.');p[key].forEach((x,i)=>{if(!x||typeof x.name!=='string'||!x.name.trim())errors.push(key+' '+(i+1)+' 이름이 필요합니다.');if(check)check(x,i);});};
 checkPool('classes',d.classes||[],x=>{if(typeof x.description!=='string')errors.push('캐릭터 '+x.id+' 설명이 필요합니다.');Object.entries(x.startingStats||{}).forEach(([k,v])=>{if(!stats.has(k)||derived.has(k)||!Number.isInteger(v)||v<0||v>100)errors.push('캐릭터 '+x.id+' 시작 스탯 오류: '+k);});});
 checkPool('items',d.items||[],x=>{if(typeof x.description!=='string'||!x.description.trim())errors.push('아이템 '+x.id+' 설명이 필요합니다.');if(!x.effect||typeof x.effect!=='object'||Array.isArray(x.effect)||Object.keys(x.effect).length>1)errors.push('아이템 '+x.id+' effect는 스탯 최대 하나입니다.');Object.entries(x.effect||{}).forEach(([k,v])=>{if(!stats.has(k)||derived.has(k))errors.push('아이템 '+x.id+' 효과 스탯 오류: '+k);if(!Number.isInteger(v)||v< -20||v>20)errors.push('아이템 '+x.id+' 효과는 -20~20 정수입니다.');});});
 checkPool('skills',d.skills||[],null);
 if(!Array.isArray(p.scenes))errors.push('scenes 배열이 필요합니다.');else{const got=new Set(p.scenes.map(x=>x?.id)),want=new Set(Object.keys(d.scenes));for(const id of want)if(!got.has(id))errors.push('scenes에 '+id+'가 없습니다.');for(const id of got)if(!want.has(id))errors.push('새 장면 ID '+id+'를 사용할 수 없습니다.');p.scenes.forEach(x=>{const s=d.scenes[x.id];if(!s)return;if(typeof x.title!=='string'||!x.title.trim()||typeof x.text!=='string'||!x.text.trim())errors.push('장면 '+x.id+' 제목·본문이 필요합니다.');if(!Array.isArray(x.choices)||x.choices.length!==s.choices.length)errors.push('장면 '+x.id+' 선택지 수는 '+s.choices.length+'개여야 합니다.');else x.choices.forEach((c,i)=>{if(c.no!==i+1||typeof c.label!=='string'||!c.label.trim())errors.push('장면 '+x.id+' 선택 '+(i+1)+' 형식 오류');});});}
 if(!errors.length)warn.push('형식 통과. 장면 설명·선택 문구·아이템 설명이 실제 보존 규칙과 같은 뜻인지 사람이 확인해야 합니다.');return {errors:[...new Set(errors)],warn};}
 function applyContent(d,p){const out=copy(d);out.meta={...out.meta,title:p.meta.title,tagline:p.meta.tagline||'',theme:p.meta.theme};Object.assign(out.stats,p.initialStats);for(const key of ['classes','items','skills'])p[key].forEach(x=>{const y=out[key].find(v=>v.id===x.id);y.name=x.name;if('description'in x)y.description=x.description;if(key==='classes')y.startingStats=copy(x.startingStats||{});if(key==='items')y.effect=copy(x.effect||{});});p.scenes.forEach(x=>{const s=out.scenes[x.id];s.title=x.title;s.text=x.text;x.choices.forEach((c,i)=>s.choices[i].label=c.label);});return out;}
 function testPrompt(d){return `아래 BRANCH 게임 데이터를 테스트할 JSON 배열을 만들어라. 설명문·코드펜스 없이 배열만 출력해라.\n\n각 테스트 형식:\n{"name":"테스트 이름","start":{"sceneId":"장면ID","classId":"캐릭터ID 또는 null","stats":{"바꿀 기본 스탯":숫자},"inventory":["아이템ID"],"skills":["스킬ID"]},"choiceNo":1,"expected":{"available":true,"sceneId":"선택 후 장면ID","stats":{"확인할 스탯":예상값}}}\n\n규칙:\n- choiceNo는 화면의 1번부터 시작한다. 캐릭터가 있는 게임에서는 classId를 반드시 실제 캐릭터 ID로 쓴다.\n- stats에는 바꿀 기본 스탯만 쓰고 계산 스탯은 쓰지 않는다.\n- available=false이면 sceneId와 stats는 선택 전 상태를 기준으로 쓴다.\n- 보유 아이템 지정은 획득 효과를 다시 적용하지 않는다. 스킬 지정은 획득 조건을 우회한다.\n- 정상 경로 2개, 조건 바로 아래/충족 경계 2개, 아이템 최초/중복 2개, 자동 엔딩 우선순위 2개로 총 8개를 만든다.\n- 실제 규칙에서 계산한 예상값을 넣되 실행했다고 주장하지 않는다.\n\n게임 데이터:\n${JSON.stringify(d,null,2)}`;}
 function validateTests(d,rows){const errors=[];if(!Array.isArray(rows)||!rows.length||rows.length>30)return {errors:['1~30개의 테스트 배열이 필요합니다.']};rows.forEach((t,i)=>{const tag=(i+1)+'번';if(!t||typeof t.name!=='string')errors.push(tag+' name 필요');const s=t?.start||{};if(!own(d.scenes,s.sceneId))errors.push(tag+' sceneId 오류');if((d.classes||[]).length&&!d.classes.some(x=>x.id===s.classId))errors.push(tag+' classId는 실제 캐릭터 ID가 필요');else if(s.classId!=null&&!d.classes.some(x=>x.id===s.classId))errors.push(tag+' classId 오류');Object.keys(s.stats||{}).forEach(k=>{if(!own(d.stats,k)||d.derivedStats?.some(r=>r.target===k))errors.push(tag+' stats 오류 '+k);});for(const [key,pool]of [['inventory','items'],['skills','skills']])if(!Array.isArray(s[key]||[])||(s[key]||[]).some(id=>!d[pool].some(x=>x.id===id)))errors.push(tag+' '+key+' 오류');const scene=d.scenes[s.sceneId];if(!Number.isInteger(t.choiceNo)||t.choiceNo<1||t.choiceNo>(scene?.choices?.length||0))errors.push(tag+' choiceNo 오류');if(typeof t?.expected?.available!=='boolean')errors.push(tag+' expected.available 필요');Object.keys(t?.expected?.stats||{}).forEach(k=>{if(!own(d.stats,k))errors.push(tag+' 예상 스탯 오류 '+k);});});return {errors:[...new Set(errors)]};}
 function runTests(d,rows){return rows.map(t=>{try{const c=d.classes.find(x=>x.id===t.start.classId),base={...d.stats,...(c?.startingStats||{}),...(t.start.stats||{})},game=GameRules.create(d);game.restore({sceneId:t.start.sceneId,classId:t.start.classId||null,stats:base,inventory:t.start.inventory||[],skills:t.start.skills||[],rng:12345},true);const before=game.getState(),choice=d.scenes[before.sceneId]?.choices[t.choiceNo-1],actualAvailable=!!choice&&game.reasons(choice).length===0;const diffs=[];if(actualAvailable!==t.expected.available)diffs.push('선택 가능 예상 '+t.expected.available+' / 실제 '+actualAvailable);if(actualAvailable)game.choose(t.choiceNo-1);const after=game.getState();if(t.expected.sceneId&&after.sceneId!==t.expected.sceneId)diffs.push('장면 예상 '+t.expected.sceneId+' / 실제 '+after.sceneId);Object.entries(t.expected.stats||{}).forEach(([k,v])=>{if(after.stats[k]!==v)diffs.push(k+' 예상 '+v+' / 실제 '+after.stats[k]);});return {name:t.name,pass:!diffs.length,diffs,before,after};}catch(e){return {name:t.name,pass:false,diffs:['실행 오류: '+e.message]};}});}
 function validateItems(d,rows){const errors=[],derived=new Set((d.derivedStats||[]).map(r=>r.target)),allowed=new Set(Object.keys(d.stats).filter(k=>!derived.has(k))),seen=new Set((d.items||[]).map(x=>x.id));if(!Array.isArray(rows)||!rows.length||rows.length>100)return {errors:['1~100개의 아이템 배열이 필요합니다.']};rows.forEach((x,i)=>{const tag=(i+1)+'번';if(!x||typeof x!=='object'||Array.isArray(x)){errors.push(tag+' 객체 필요');return;}if(typeof x.id!=='string'||!/^[A-Za-z0-9_]+$/.test(x.id)||['__proto__','constructor','prototype'].includes(x.id))errors.push(tag+' ID 형식 오류');if(seen.has(x.id))errors.push(tag+' 중복 ID '+x.id);seen.add(x.id);if(typeof x.name!=='string'||!x.name.trim()||typeof x.description!=='string'||!x.description.trim())errors.push(tag+' 이름·설명 필요');if(!x.effect||typeof x.effect!=='object'||Array.isArray(x.effect)||Object.keys(x.effect).length!==1){errors.push(tag+' effect에 스탯 하나 필요');return;}Object.entries(x.effect).forEach(([k,v])=>{if(!allowed.has(k))errors.push(tag+' 허용되지 않는 스탯 '+k);if(!Number.isInteger(v)||v< -20||v>20)errors.push(tag+' 효과값은 -20~20 정수');});});return {errors:[...new Set(errors)]};}
 function ai(b){const d=b.get(),root=document.getElementById('tabContent');root.replaceChildren();const wrap=E('div',undefined,'lab ai-studio');wrap.append(E('div','BRANCH / AI CUSTOMIZE & TEST','eyebrow'),E('h2','AI로 내 게임을 만들고, AI 결과를 다시 검사해요.'),E('p','프롬프트 → AI 데이터 → 형식 검사 → 게임 적용 → 테스트 생성 → 실제 엔진 비교 순서로 진행합니다.'));root.appendChild(wrap);modelNote(wrap);
  const guide=E('div',undefined,'ai-cycle');['1 기획 입력','2 AI 개인화 팩','3 사람의 의미 확인','4 AI 테스트 팩','5 실제 엔진 비교','6 프롬프트·데이터 수정'].forEach(x=>guide.appendChild(E('span',x)));wrap.appendChild(guide);const flow=E('section',undefined,'ai-flow-map');flow.append(E('h3','무엇이 어디로 연결되나요?'),E('p','아래 세 흐름은 서로 다른 역할입니다. 개인화와 아이템은 게임을 바꾸고, 테스트는 게임을 바꾸지 않습니다.'));const rows=E('div',undefined,'ai-flow-rows');[['A 기획 입력','→','ChatGPT · Claude','→','B 개인화 JSON','→','현재 게임 전체 변경'],['현재 게임','→','C 테스트 프롬프트','→','AI 테스트 JSON','→','예상과 실제 비교만'],['D 아이템 요청','→','AI 아이템 JSON','→','아이템 목록','→','장면 선택지에 연결']].forEach(parts=>{const row=E('div',undefined,'ai-flow-row');parts.forEach((x,i)=>row.appendChild(E(i%2?'span':'b',x,i%2?'flow-arrow':'')));rows.appendChild(row);});flow.appendChild(rows);const files=E('div',undefined,'ai-file-map');[['개인화 JSON','B에서 불러오기 또는 붙여넣기','제목·장면·캐릭터·아이템·허용 수치를 현재 게임에 적용'],['AI 테스트 JSON','C에서 불러오기 또는 붙여넣기','예상과 실제를 비교하며 게임 데이터는 변경하지 않음'],['아이템 JSON 배열','D에 붙여넣기','아이템 목록에 등록한 뒤 장면 선택지에 연결해야 등장'],['story-data.js','상단 저장 → 제작 데이터 저장','현재 게임 전체를 다음 수업에 다시 편집'],['my-story.html','상단 저장 → 플레이 HTML 저장','에디터 없이 실행하는 최종 게임']].forEach(([a,b,c])=>{const row=E('div');row.append(E('strong',a),E('span',b),E('small',c));files.appendChild(row);});flow.appendChild(files);const jumps=E('div',undefined,'ai-jumps');[['A 기획으로','aiStepA'],['B 개인화 적용','aiStepB'],['C 테스트 실행','aiStepC'],['D 아이템 추가','aiStepD']].forEach(([label,id])=>jumps.appendChild(B(label,()=>document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'}))));flow.appendChild(jumps);wrap.appendChild(flow);
  const plan=box(wrap,'A. 나만의 게임 기획','다섯 칸을 바꾸면 같은 규칙에서도 서로 다른 게임을 만들 수 있습니다.');plan.id='aiStepA';plan.appendChild(E('div','출력: AI에 보낼 프롬프트 · 아직 게임은 바뀌지 않음','ai-output-tag neutral'));const grid=E('div',undefined,'ai-fields');plan.appendChild(grid);const genre=field(grid,'장르·소재','미스터리 탈출','예: 우주 생존, 판타지 탐험'),setting=field(grid,'배경','정전된 미래 도시','예: 해저 연구소'),mood=field(grid,'분위기','긴장감 있지만 잔혹하지 않음'),goal=field(grid,'플레이어 목표','단서를 모아 안전한 출구를 찾기'),words=field(grid,'꼭 넣을 단어','신호, 잠긴 문, 선택');const prompt=area(plan,'AI에게 보낼 개인화 프롬프트');prompt.readOnly=true;const make=()=>{prompt.value=contentPrompt(d,{genre:genre.value,setting:setting.value,mood:mood.value,goal:goal.value,words:words.value});};make();plan.append(B('프롬프트 다시 만들기',make),B('프롬프트 선택',()=>selectText(prompt),'primary'));
  const content=box(wrap,'B. AI 개인화 팩 검사·적용','AI 응답의 JSON 객체를 붙입니다. ID·연결·조건은 보존하고 표현과 허용 수치만 바꿉니다.');content.id='aiStepB';content.appendChild(E('div','입력: 개인화 JSON → 결과: 현재 게임 전체 변경','ai-output-tag changes'));const contentArea=area(content,'개인화 JSON'),contentFile=E('input');contentFile.type='file';contentFile.accept='.json,application/json';contentFile.hidden=true;contentFile.onchange=()=>{const f=contentFile.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{contentArea.value=String(reader.result);checked=null;apply.disabled=true;out.textContent=f.name+'을 읽었습니다. 형식 검사를 누르세요.';};reader.onerror=()=>{out.textContent='파일을 읽지 못했습니다. 다른 JSON 파일을 선택하세요.';};reader.readAsText(f);contentFile.value='';};let checked=null;const out=E('pre','아직 검사하지 않았습니다.');const apply=B('검사한 개인화 팩 적용',()=>{if(!checked)throw Error('먼저 오류 없이 검사하세요.');if(!confirm('현재 제목·문장·이름·허용 수치를 AI 개인화 팩으로 바꿀까요? 먼저 제작 데이터를 저장하면 안전합니다.'))return;const next=applyContent(d,checked),vr=GameRules.validate(next);if(vr.errors.length)throw Error(vr.errors.join('\n'));b.set(next);if(b.notify)b.notify('개인화가 현재 게임에 적용됐습니다. 상단 ▶ 플레이로 확인한 뒤 저장 ▾에서 제작 데이터를 보관하세요.');},'primary');apply.disabled=true;content.append(B('개인화 JSON 파일 불러오기',()=>contentFile.click()),contentFile,B('형식 검사',()=>{try{const p=JSON.parse(strip(contentArea.value)),r=validateContent(d,p);checked=r.errors.length?null:p;apply.disabled=!!r.errors.length;out.textContent=r.errors.concat(r.warn).join('\n');}catch(e){checked=null;apply.disabled=true;out.textContent='JSON 읽기 실패: '+e.message;}}),apply,out,E('p','검사 통과 뒤에도 선택 문구가 실제 다음 장면·조건·효과와 같은 뜻인지 사람이 확인하세요. 적용 후 데이터 검사와 플레이를 실행합니다.','notice'));
  const tester=box(wrap,'C. 현재 게임의 AI 테스트 팩','개인화된 현재 게임을 AI에게 주고 예상 테스트 데이터를 받습니다. AI 예상은 정답이 아니며 실제 엔진 결과와 비교합니다.');tester.id='aiStepC';tester.appendChild(E('div','입력: AI 테스트 JSON → 결과: 예상·실제 비교 · 게임 데이터는 변경하지 않음','ai-output-tag checks'));const tp=area(tester,'테스트 생성 프롬프트');tp.readOnly=true;tp.value=testPrompt(d);tester.append(B('테스트 프롬프트 다시 만들기',()=>tp.value=testPrompt(b.get())),B('프롬프트 선택',()=>selectText(tp),'primary'));const tests=area(tester,'AI 테스트 JSON 배열','[ { "name": "...", ... } ]'),testFile=E('input');testFile.type='file';testFile.accept='.json';testFile.hidden=true;testFile.onchange=()=>{const f=testFile.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{tests.value=String(reader.result);};reader.readAsText(f);testFile.value='';};const saveTests=()=>{if(!tests.value.trim())throw Error('저장할 테스트 JSON이 없습니다.');JSON.parse(strip(tests.value));const u=URL.createObjectURL(new Blob([strip(tests.value)],{type:'application/json'})),a=E('a');a.href=u;a.download='ai-tests.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1500);};const results=E('div',undefined,'ai-test-results');tester.append(B('테스트 JSON 불러오기',()=>testFile.click()),B('테스트 JSON 저장',saveTests),testFile,B('테스트 형식 검사·실행',()=>{let rows;try{rows=JSON.parse(strip(tests.value));}catch(e){results.replaceChildren(E('p','JSON 읽기 실패: '+e.message,'notice bad'));return;}const d2=b.get(),v=validateTests(d2,rows);if(v.errors.length){results.replaceChildren(E('pre',v.errors.join('\n')));return;}const run=runTests(d2,rows);results.replaceChildren(E('div','테스트 실행은 현재 게임을 수정하지 않았습니다.','ai-test-only'),E('h4','실행 결과 · '+run.filter(x=>x.pass).length+'/'+run.length+' 예상 일치'));run.forEach((r,i)=>{const card=E('article',undefined,'ai-test '+(r.pass?'pass':'fail'));card.append(E('strong',(r.pass?'일치 ':'차이 ')+'T'+(i+1)+' · '+r.name),E('p',r.pass?'AI 예상과 실제 엔진 결과가 같습니다.':r.diffs.join(' / ')));if(!r.pass)card.append(E('small','AI 예상이 틀렸는지, 게임 설정이 의도와 다른지 시작 상태와 규칙을 확인하세요.'));results.appendChild(card);});},'primary'),results);
  const item=box(wrap,'D. 아이템 생성 → 검사 → 게임 연결','AI가 만든 JSON을 아이템 목록에 등록한 뒤, 장면 선택지의 ‘획득 아이템’으로 연결해야 플레이에 등장합니다.');item.id='aiStepD';item.appendChild(E('div','입력: 아이템 JSON → 결과: 아이템 목록 추가 · 장면 연결 전에는 플레이에 등장하지 않음','ai-output-tag changes'));const allowed=Object.keys(d.stats).filter(k=>!d.derivedStats?.some(x=>x.target===k));const ip=area(item,'아이템 요청문');ip.value='게임 아이템 3개를 JSON 배열로 만들어줘. 필드는 id, name, description, effect야. id는 영문·숫자·밑줄, effect에는 '+allowed.join(', ')+' 중 하나만 사용하고 값은 -20~20 정수로 써. description은 실제 효과·부호와 일치해야 해. JSON 외 문장은 제외해.';ip.readOnly=true;item.append(E('p','1. 요청문 선택 → Ctrl+C → ChatGPT 또는 Claude에 붙여넣기','ai-mini-step'),B('1. 요청문 선택',()=>selectText(ip)));item.append(E('p','2. AI가 답한 대괄호 [ ... ] 전체를 아래 칸에 붙여넣기','ai-mini-step'));const itemArea=area(item,'AI 아이템 JSON 배열','[ { \"id\": \"...\", ... } ]'),itemOut=E('pre','아직 검사하지 않았습니다.');let goodItems=null;const addItems=B('4. 아이템 라이브러리에 추가',()=>{if(!goodItems)throw Error('먼저 오류 없이 검사하세요.');const first=goodItems[0].id,next=copy(b.get());next.items.push(...goodItems.map(x=>({id:x.id,name:x.name,description:x.description,effect:copy(x.effect),icon:''})));b.set(next);if(b.openAsset)b.openAsset('items',first,'아이템을 등록했습니다. 다음은 장면 지도에서 선택지의 획득 아이템으로 연결하세요.');},'primary');addItems.disabled=true;item.append(B('3. 아이템 형식 검사',()=>{try{const rows=JSON.parse(strip(itemArea.value)),v=validateItems(b.get(),rows);goodItems=v.errors.length?null:rows;addItems.disabled=!!v.errors.length;itemOut.textContent=v.errors.join('\n')||(rows.length+'개 형식 통과. description의 스탯·방향·값과 effect를 사람이 비교한 뒤 추가하세요.');}catch(e){goodItems=null;addItems.disabled=true;itemOut.textContent='JSON 읽기 실패: '+e.message;}}),addItems,itemOut,E('div','5. 실제 게임에 연결: 왼쪽 장면 지도 → 아이템을 받을 장면 선택 → 기존 선택지 또는 + 추가 → 조건 · 효과 · 획득 펼치기 → 획득 아이템에서 방금 만든 아이템 선택 → ▶ 플레이로 획득 확인','ai-connect-guide'));
 }
 g.AIStudioTools={contentSpec,contentPrompt,validateContent,applyContent,testPrompt,validateTests,runTests,validateItems};
 g.Lab.ai=ai;
})(window);
