(function(g){
'use strict';
const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
function init(container,data,options={}){
 let game;try{game=GameRules.create(data);}catch(e){container.replaceChildren(node('div','데이터를 확인하세요: '+e.message,'p-alert'));return {reset:()=>{},getState:()=>null,getLogs:()=>[],setState:()=>{throw e;}};}
 let root,phase='cover',previous=null,feedbackTimer=null,lastAction='';
 const name=(pool,id)=>data[pool]?.find(x=>x.id===id)?.name||id;
 const url=(f,kind)=>/^data:image\//.test(f)?f:(kind==='video'?'videos/':'images/')+f;
 function button(label,fn,cls){const b=node('button',label,cls);b.type='button';b.onclick=()=>{try{fn();}catch(e){message('확인해주세요',e.message);}};return b;}
 function shell(){clearTimeout(feedbackTimer);container.replaceChildren();root=node('div',undefined,'branch-player');root.dataset.theme=data.meta?.theme||'forest';container.appendChild(root);const top=node('header',undefined,'p-top'),actions=node('div',undefined,'p-top-actions');top.append(node('span','B↗','p-logo'),node('span',data.meta?.title||'이름 없는 이야기','p-name'));actions.append(button('불러오기',()=>saveDialog(true)));if(game.getState().started)actions.prepend(button('저장',()=>saveDialog(false)),button('처음으로',()=>confirmReset()));top.appendChild(actions);root.appendChild(top);return root;}
 function message(title,text){const overlay=node('div',undefined,'p-overlay'),box=node('section',undefined,'p-save-box');box.append(node('h2',title),node('p',text),button('닫기',()=>overlay.remove()));overlay.appendChild(box);root.appendChild(overlay);box.querySelector('button').focus();}
 function confirmReset(){const overlay=node('div',undefined,'p-overlay'),box=node('section',undefined,'p-save-box');box.append(node('h2','처음으로 돌아갈까요?'),node('p','진행을 이어가려면 저장 코드를 먼저 보관하세요.'),button('돌아가기',()=>{game.reset();phase='cover';previous=null;render();}),button('계속 플레이',()=>overlay.remove()));overlay.appendChild(box);root.appendChild(overlay);}
 function saveDialog(load){const overlay=node('div',undefined,'p-overlay'),box=node('section',undefined,'p-save-box'),text=node('textarea'),error=node('p',undefined,'error');text.setAttribute('aria-label',load?'불러올 저장 코드':'게임 저장 코드');box.append(node('h2',load?'이야기 이어가기':'지금의 이야기를 보관하세요'),node('p','같은 게임의 저장 코드를 사용하세요. 코드에는 현재 장면과 캐릭터 상태가 들어 있어요.'));if(!load){const bytes=new TextEncoder().encode(JSON.stringify(game.getState()));let raw='';bytes.forEach(b=>raw+=String.fromCharCode(b));text.value=btoa(raw);text.readOnly=true;}box.appendChild(text);if(load)box.appendChild(button('이어하기',()=>{try{const bytes=Uint8Array.from(atob(text.value.trim()),c=>c.charCodeAt(0));game.restore(JSON.parse(new TextDecoder().decode(bytes)));phase='play';render();}catch(e){error.textContent='코드를 읽을 수 없어요. '+e.message;}}));else box.appendChild(button('코드 선택',()=>{text.focus();text.select();}));box.append(button('닫기',()=>overlay.remove()),error);overlay.appendChild(box);root.appendChild(overlay);text.focus();}
 function art(parent,mood,source,video){const a=node('div',undefined,'p-art');a.dataset.mood=mood||'';['moon','floor','pillar a','pillar b','lintel','door','mist','figure'].forEach(cls=>a.appendChild(node('div',undefined,cls)));for(let i=0;i<16;i++){const s=node('i',undefined,'spark');s.style.left=(40+(i*17)%55)+'%';s.style.top=(15+(i*23)%70)+'%';s.style.animationDelay=(-i*.7)+'s';a.appendChild(s);}parent.appendChild(a);if(!source)return null;const m=node(video?'video':'img',undefined,'p-media');m.src=url(source,video?'video':'image');if(video){m.playsInline=true;m.controls=true;m.autoplay=true;}else m.alt='';m.addEventListener('error',()=>{m.remove();parent.appendChild(node('div','미디어를 열 수 없어 기본 배경으로 표시합니다.','p-media-notice'));});parent.append(m,node('div',undefined,'p-media-shade'));return m;}
 function begin(){if(data.classes?.length){phase='classes';render();}else{game.start();phase='play';render();}}
 function renderCover(stage){art(stage,'start',data.scenes[data.startScene]?.image,false);const c=node('section',undefined,'p-cover');c.append(node('div',data.meta?.coverLabel||'AN INTERACTIVE STORY','p-eyebrow'),node('h1',data.meta?.title||'이름 없는 이야기'),node('p',data.meta?.tagline||'선택 하나로 달라지는 이야기.\n문 너머의 세계가 당신을 기다립니다.','tagline'));const b=button('',begin,'p-start');b.append(node('span','이야기 시작'),node('span','↗'));c.append(b,button('저장한 이야기 이어가기',()=>saveDialog(true),'continue'));const meta=node('div',undefined,'cover-meta');[[Object.keys(data.scenes).length,'SCENES'],[Object.keys(data.endings||{}).length,'ENDINGS'],['YOU','DECIDE']].forEach(([n,label])=>{const box=node('div');box.append(node('strong',n),node('span',label));meta.appendChild(box);});c.appendChild(meta);stage.append(c,node('div',data.meta?.author?'A STORY BY '+data.meta.author:'EVERY CHOICE LEAVES A TRACE','p-edition'));}
 function renderClasses(stage){art(stage,'classes');const page=node('section',undefined,'p-class-page');page.append(node('div','CHOOSE YOUR PERSPECTIVE','p-eyebrow'),node('h1','누구의 시선으로 시작할까요?'),node('p','같은 갈림길도, 가진 능력에 따라 다른 길이 됩니다.'));const grid=node('div',undefined,'p-class-grid');data.classes.forEach((c,i)=>{const b=button('',()=>{game.start(c.id);phase='play';render();},'p-class-card');b.setAttribute('aria-label',c.name+' 선택');b.append(node('span',i%2?'◈':'⌘','class-symbol'),node('strong',c.name),node('p',c.description||'당신만의 방식으로 이야기를 이어가세요.'),node('small',Object.entries(c.startingStats||{}).map(([k,v])=>k+' '+v).join(' / ')));grid.appendChild(b);});page.appendChild(grid);stage.appendChild(page);}
 function sidebar(s){const side=node('aside',undefined,'p-sidebar'),c=data.classes?.find(x=>x.id===s.classId),who=node('div',undefined,'p-persona');who.append(node('span',c?.name?.slice(0,1)||'B','p-avatar'));const label=node('div');label.append(node('strong',c?.name||'플레이어'),node('small','YOUR CHARACTER'));who.appendChild(label);side.append(who,node('h2','STATUS'));Object.entries(s.stats).forEach(([k,v])=>{const row=node('div',undefined,'p-stat'),line=node('div',undefined,'p-stat-label'),track=node('div',undefined,'p-stat-track'),bar=node('i');line.append(node('span',k),node('b',Number(v.toFixed(2))));const max=data.statBounds?.[k]?.max??Math.max(data.stats[k]||100,1),min=data.statBounds?.[k]?.min??0;bar.style.width=Math.max(0,Math.min(100,(v-min)/(max-min||1)*100))+'%';track.appendChild(bar);row.append(line,track);side.appendChild(row);});const inv=node('div',undefined,'p-inventory');inv.appendChild(node('h2','INVENTORY'));if(!s.inventory.length)inv.appendChild(node('p','아직 발견한 것이 없어요.','p-empty'));s.inventory.forEach(id=>{const it=data.items.find(x=>x.id===id),n=node('div',undefined,'p-item');n.title=it.description||it.name;if(it.icon){const img=node('img');img.src=url(it.icon,'image');img.alt='';img.onerror=()=>img.remove();n.appendChild(img);}else n.appendChild(node('span','◇'));n.appendChild(node('span',it.name));inv.appendChild(n);});s.skills.forEach(id=>inv.appendChild(node('span','✦ '+name('skills',id),'p-skill')));side.appendChild(inv);return side;}
 function reasons(c){return game.reasons(c).map(t=>t.replace(/필요 아이템: (.+)/,(_,id)=>'필요 아이템: '+name('items',id)).replace(/필요 스킬: (.+)/,(_,id)=>'필요 스킬: '+name('skills',id)).replace(/필요 직업: (.+)/,(_,id)=>'필요 캐릭터: '+name('classes',id)));}
 function play(stage){const s=game.getState(),scene=data.scenes[s.sceneId],ending=Object.values(data.endings||{}).find(x=>x.sceneId===s.sceneId);const media=art(stage,s.sceneId,ending?(ending.video||ending.image||scene.image):(scene.video||scene.image),ending?!!ending.video:!!scene.video);if(ending){const end=node('section',undefined,'p-ending');end.append(node('div','◇','end-mark'),node('div','THE END · '+(data.meta?.title||''),'p-eyebrow'),node('h1',ending.title||'이야기의 끝'),node('p',scene.text||''),button('다른 선택으로 다시 시작 ↗',()=>{game.reset();phase='cover';render();},'p-start'));if(options.showLogs)end.appendChild(logs());stage.appendChild(end);return;}
 const grid=node('div',undefined,'p-play-grid'),story=node('section',undefined,'p-narrative');story.append(node('div','SCENE '+String(Object.keys(data.scenes).indexOf(s.sceneId)+1).padStart(2,'0'),'p-scene-number'),node('h1',scene.title||'다음 선택'),node('p',scene.text||'','p-story'));const choices=node('div',undefined,'p-choices');let available=0;scene.choices.forEach((c,i)=>{const why=reasons(c),b=button('',()=>{choose(i);},'p-choice');b.setAttribute('aria-label',c.label);const text=node('span',undefined,'choice-copy');text.appendChild(node('span',c.label));if(why.length){b.disabled=true;text.appendChild(node('small',why.join(' · ')));}else available++;b.append(node('span',String(i+1).padStart(2,'0'),'ordinal'),text,node('span',why.length?'·':'↗','arrow'));choices.appendChild(b);});if(!available)choices.appendChild(node('p','지금 상태에서는 선택할 수 있는 길이 없습니다. 저장한 지점을 불러오거나 다시 시작해보세요.','p-alert'));story.appendChild(choices);if(previous){story.appendChild(node('p','최근 행동 · '+lastAction,'p-recent-action'));const changes=Object.entries(s.stats).filter(([k,v])=>previous.stats[k]!==v).map(([k,v])=>k+' '+(v-previous.stats[k]>0?'+':'')+Number((v-previous.stats[k]).toFixed(2)));if(changes.length)story.appendChild(node('p',changes.join('   /   '),'p-delta'));}if(options.showLogs)story.appendChild(logs());grid.append(story,sidebar(s));stage.appendChild(grid);
 if(scene.video&&media){choices.hidden=true;const controls=node('div',undefined,'p-video-controls');const reveal=()=>{choices.hidden=false;controls.remove();};controls.append(button('영상 재생',()=>media.play().catch(()=>{})),button('영상 건너뛰기',reveal));media.addEventListener('ended',reveal);media.addEventListener('error',reveal);stage.prepend(controls);}
 }
 function choose(i){
 const before=game.getState(),choice=data.scenes[before.sceneId]?.choices[i];
 const result=game.choose(i);if(!result)return result;
 previous=before;lastAction=choice.label;phase='play';render();feedback(before,game.getState(),choice);return result;
 }
 function feedback(before,after,choice){
 const changes=Object.entries(after.stats).filter(([k,v])=>before.stats[k]!==v);
 const items=after.inventory.filter(id=>!before.inventory.includes(id));
 const skills=after.skills.filter(id=>!before.skills.includes(id));
 const attack=/공격|타격|베기|쏘기/.test(choice.label);
 if(!changes.length&&!items.length&&!skills.length&&!attack)return;
 const overlay=node('div',undefined,'p-feedback'+(attack?' is-attack':''));
 overlay.setAttribute('role','status');overlay.setAttribute('aria-live','polite');
 const card=node('section',undefined,'p-feedback-card');
 card.append(node('div',attack?'⚔':items.length?'◇':skills.length?'✦':'↗','p-feedback-symbol'),node('h2',attack?'공격!':items.length?'아이템 획득':skills.length?'스킬 획득':'상태 변화'),node('p',choice.label,'p-feedback-action'));
 for(const id of items){const it=data.items.find(x=>x.id===id),row=node('div',undefined,'p-loot');if(it.icon){const img=node('img');img.src=url(it.icon,'image');img.alt='';img.onerror=()=>img.remove();row.appendChild(img);}row.append(node('strong',it.name),node('span',it.description||'가방에 추가되었어요.'));card.appendChild(row);}
 skills.forEach(id=>card.appendChild(node('div','✦ '+name('skills',id)+' 습득','p-loot')));
 const deltas=node('div',undefined,'p-feedback-deltas');changes.forEach(([k,v])=>{const delta=Number((v-before.stats[k]).toFixed(2)),line=node('div',undefined,delta<0?'loss':'gain');line.append(node('span',k),node('strong',(delta>0?'+':'')+delta),node('small',before.stats[k]+' → '+v));deltas.appendChild(line);});card.appendChild(deltas);
 const stage=root.querySelector('.p-stage');if(stage)stage.inert=true;const close=()=>{clearTimeout(feedbackTimer);if(stage)stage.inert=false;overlay.remove();};card.appendChild(button('계속하기',close,'p-feedback-close'));overlay.appendChild(card);root.appendChild(overlay);feedbackTimer=setTimeout(close,items.length||skills.length?4000:2200);
 }
 function logs(){const detail=node('details',undefined,'p-log');detail.open=true;detail.append(node('summary','변화 보기'),node('pre',game.getLogs().join('\n')||'아직 변화가 없습니다.'));return detail;}
 function render(){shell();const stage=node('div',undefined,'p-stage');root.appendChild(stage);if(phase==='cover')renderCover(stage);else if(phase==='classes')renderClasses(stage);else play(stage);if(options.onChange)options.onChange(game.getState(),game.getLogs());}
 render();return {reset:()=>{game.reset();phase='cover';previous=null;render();},getState:game.getState,getLogs:game.getLogs,setState:s=>{game.restore(s,true);phase='play';previous=null;render();},choose};
}
g.StoryEngine={init};
})(window);
