(function(g){
'use strict';
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const btn=(text,fn,primary=false)=>{const b=el('button',text,primary?'primary':'');b.type='button';b.onclick=()=>{try{fn();}catch(e){alert(e.message);}};return b;};
function input(type,value,change){const n=el('input');n.type=type;n.value=value??'';if(change)n.onchange=()=>change(type==='number'?Number(n.value):n.value);return n;}
function select(values,value,change){const n=el('select');values.forEach(v=>{const pair=Array.isArray(v)?v:[v,v];const o=el('option',pair[1]);o.value=pair[0];n.appendChild(o);});n.value=value??'';if(change)n.onchange=()=>change(n.value);return n;}
function field(parent,text,n){n.setAttribute('aria-label',text);const l=el('label',text);l.appendChild(n);parent.appendChild(l);return n;}
function card(parent,title){const c=el('section',undefined,'lab-card');if(title)c.appendChild(el('h3',title));parent.appendChild(c);return c;}
function root(title,sub){const parent=document.getElementById('tabContent');parent.replaceChildren();const r=el('div',undefined,'lab');r.append(el('div','BRANCH / CREATIVE TOOLS','eyebrow'),el('h2',title),el('p',sub));parent.appendChild(r);return r;}
function notice(parent,text,bad=false){const n=el('p',text,'notice'+(bad?' bad':''));parent.appendChild(n);return n;}
function rules(b){const d=b.get(),r=root('스탯 사이에 관계를 만들어요.','기본 스탯을 바꾸면 계산 스탯이 자동으로 바뀝니다. 저장은 입력을 마친 뒤 적용됩니다.');d.statBounds=d.statBounds||{};d.derivedStats=d.derivedStats||[];
 const stats=Object.keys(d.stats),base=card(r,'1. 시작값과 범위');
 stats.forEach(k=>{const row=el('div',undefined,'row'),derived=d.derivedStats.some(x=>x.target===k),bounds=d.statBounds[k]||{};base.appendChild(row);const val=field(row,k+(derived?' (자동 계산)':''),input('number',d.stats[k],v=>{d.stats[k]=v;b.save();}));val.disabled=derived;
 ['min','max'].forEach((key,i)=>{const n=input('number',bounds[key]);n.placeholder='제한 없음';n.onchange=()=>{d.statBounds[k]=d.statBounds[k]||{};if(n.value==='')delete d.statBounds[k][key];else d.statBounds[k][key]=Number(n.value);b.save();};field(row,i?'최댓값':'최솟값',n);});});
 base.appendChild(btn('스탯 추가',()=>{const k=prompt('새 스탯 이름');if(!k)return;if(['__proto__','constructor','prototype'].includes(k)||Object.hasOwn(d.stats,k))throw Error('다른 스탯 이름을 입력하세요.');d.stats[k]=0;b.save();rules(b);}));
 const derived=card(r,'2. 계산 규칙');notice(derived,'계산 대상 = 원본 × 배율 + 상수 + 더할 스탯. 예: 공격력 = 기본공격력 × 1 + 0 + 무기보정. 계산 대상에는 아이템 효과를 직접 주지 마세요.');
 d.derivedStats.forEach((rule,i)=>{const row=el('div',undefined,'row');derived.appendChild(row);[['target','계산 대상'],['source','원본'],['factor','배율'],['offset','상수'],['bonus','더할 스탯']].forEach(([key,label])=>field(row,label,['factor','offset'].includes(key)?input('number',rule[key],v=>{rule[key]=v;b.save();}):select(key==='bonus'?[['','없음'],...stats]:stats,rule[key],v=>{rule[key]=v;b.save();})));row.appendChild(btn('삭제',()=>{d.derivedStats.splice(i,1);b.save();rules(b);}));});
 derived.appendChild(btn('계산 규칙 추가',()=>{if(stats.length<2)throw Error('스탯을 두 개 이상 만드세요.');const target=stats.find(k=>!d.derivedStats.some(x=>x.target===k));if(!target)throw Error('모든 스탯에 계산 규칙이 있습니다.');d.derivedStats.push({target,source:stats.find(k=>k!==target),factor:1,offset:0,bonus:''});b.save();rules(b);}));
 const check=el('pre');derived.append(btn('연결 검사',()=>{const out=GameRules.validate(d);check.textContent=out.errors.length?out.errors.join('\n'):'연결 형식 정상. 바로 테스트에서 실제 값을 확인하세요.';}),btn('바로 테스트',()=>b.go('sandbox'),true),check);
 notice(r,'계산은 의존 순서대로 처리됩니다. A→B→A 순환 연결은 실행 전에 차단합니다. 행동 전 조건 확인 → 일반·연동 효과 → 첫 아이템 획득 효과 → 범위·계산 갱신 → 스킬 획득 조건 → 자동 엔딩 순서입니다. 자동 엔딩은 설정 목록 위쪽 규칙이 우선입니다.');
}
function sandbox(b){const d=b.get(),r=root('테스트 룸','이 화면의 값은 실험용입니다. 원본 게임의 시작값은 바뀌지 않습니다.');const checked=GameRules.validate(d);if(checked.errors.length){notice(r,checked.errors.join('\n'),true);return;}
 const split=el('div',undefined,'split');r.appendChild(split);const controls=card(split,'시작 상태'),play=card(split,'실행과 변화');const host=el('div');host.id='labPlay';play.appendChild(host);
 const scene=field(controls,'시작 장면',select(Object.keys(d.scenes),d.startScene));const cl=field(controls,'직업',select((d.classes||[]).length?d.classes.map(c=>[c.id,c.name]):[['','직업 없음']],d.classes?.[0]?.id||''));
 const statInputs={};function valuesForClass(){const c=d.classes.find(x=>x.id===cl.value);return {...d.stats,...(c?.startingStats||{})};}
 const statGrid=el('div',undefined,'sandbox-stats');controls.appendChild(statGrid);const initial=valuesForClass();Object.keys(d.stats).forEach(k=>{if(d.derivedStats?.some(x=>x.target===k))return;statInputs[k]=field(statGrid,k,input('number',initial[k]));});
 cl.onchange=()=>{const values=valuesForClass();Object.keys(statInputs).forEach(k=>statInputs[k].value=values[k]);};
 const boxes={};[['inventory','보유 아이템','items'],['skills','보유 스킬','skills']].forEach(([key,label,pool])=>{const wrap=el('div',undefined,'checks');wrap.appendChild(el('p',label));boxes[key]=[];(d[pool]||[]).forEach(x=>{const n=input('checkbox','');n.dataset.id=x.id;field(wrap,x.name,n);boxes[key].push(n);});controls.appendChild(wrap);});
 const seed=field(controls,'랜덤 시드 (같은 상태·행동·시드 → 같은 결과)',input('number',12345));
 notice(controls,'보유 목록은 상태를 직접 지정합니다. 아이템 효과를 다시 더하지 않으며, 스킬 획득 조건도 우회합니다. 획득 자체를 검사하려면 보유를 해제하고 게임 안에서 획득하세요.');
 let engine=StoryEngine.init(host,d,{showLogs:true});
 controls.appendChild(btn('이 상태로 실행',()=>{const stats={...d.stats};Object.entries(statInputs).forEach(([k,n])=>{if(n.value==='')throw Error(k+' 값을 입력하세요.');stats[k]=Number(n.value);});engine=StoryEngine.init(host,d,{showLogs:true});engine.setState({sceneId:scene.value,classId:cl.value||null,stats,inventory:boxes.inventory.filter(n=>n.checked).map(n=>n.dataset.id),skills:boxes.skills.filter(n=>n.checked).map(n=>n.dataset.id),rng:Number(seed.value)});},true));
 controls.appendChild(btn('원래 게임 시작',()=>{engine=StoryEngine.init(host,d,{showLogs:true});}));

}
function choiceExtras(parent,c,b){const d=b.get(),stats=Object.keys(d.stats),details=el('details',undefined,'lab-extra');details.appendChild(el('summary','추가 AND 조건 · 스탯 연동 효과'));parent.appendChild(details);
 const all=c.requiresAll||[];details.appendChild(el('p','기본 조건에 아래 조건을 모두 추가합니다.'));
 const slot=el('div');details.appendChild(slot);
 function renderReq(){slot.replaceChildren();(c.requiresAll||[]).forEach((req,i)=>{const row=el('div');const type=req.skill?'skill':req.class?'class':req.item?'item':'statAtLeast';const label=type==='statAtLeast'?Object.entries(req.statAtLeast).map(([k,v])=>k+' ≥ '+v).join(', '):type+': '+req[type];row.append(el('span',label),btn('조건 삭제',()=>{c.requiresAll.splice(i,1);b.save();renderReq();}));slot.appendChild(row);});}renderReq();
 const type=select([['skill','스킬'],['class','직업'],['item','아이템'],['statAtLeast','스탯 최소값']],'skill');const valueWrap=el('span');let value,num;
 function values(){valueWrap.replaceChildren();const pool={skill:'skills',class:'classes',item:'items'}[type.value];value=select(pool?d[pool].map(x=>[x.id,x.name]):stats,'');if(value.options.length)value.selectedIndex=0;valueWrap.appendChild(value);num=input('number',30);if(type.value==='statAtLeast')valueWrap.appendChild(num);}type.onchange=values;values();details.append(type,valueWrap,btn('AND 조건 추가',()=>{if(!value.value)throw Error('먼저 대상 데이터를 만드세요.');c.requiresAll=c.requiresAll||[];c.requiresAll.push(type.value==='statAtLeast'?{statAtLeast:{[value.value]:Number(num.value)}}:{[type.value]:value.value});b.save();renderReq();}));
 details.appendChild(el('p','연동 효과: 대상 스탯에 (행동 전 원본 × 배율 + 상수)를 더합니다. 예: 적체력에 공격력 × −1을 더하기.'));
 const fx=el('div');details.appendChild(fx);
 function renderFx(){fx.replaceChildren();(c.dynamicEffects||[]).forEach((rule,i)=>{const row=el('div');[['target','대상'],['source','원본'],['factor','배율'],['offset','상수']].forEach(([key,label])=>field(row,label,['factor','offset'].includes(key)?input('number',rule[key],v=>{rule[key]=v;b.save();}):select(stats,rule[key],v=>{rule[key]=v;b.save();})));row.appendChild(btn('효과 삭제',()=>{c.dynamicEffects.splice(i,1);b.save();renderFx();}));fx.appendChild(row);});}renderFx();details.appendChild(btn('연동 효과 추가',()=>{if(!stats.length)throw Error('스탯을 먼저 만드세요.');c.dynamicEffects=c.dynamicEffects||[];c.dynamicEffects.push({target:stats.includes('적체력')?'적체력':stats[0],source:stats.includes('공격력')?'공격력':stats[0],factor:-1,offset:0});b.save();renderFx();}));
}
function ai(b){const d=b.get(),r=root('AI가 만든 데이터를 직접 확인해요.','형식은 자동으로, 설명과 효과의 의미는 내가 확인합니다. 계정 연결 없이 복사·붙여넣기로 사용합니다.');const c=card(r,'1. 이 요청을 ChatGPT 또는 Claude에 보내세요.');const allowed=Object.keys(d.stats).filter(k=>!d.derivedStats?.some(x=>x.target===k));const promptText='게임 아이템 10개를 JSON 배열로 만들어줘. 필드는 id, name, description, effect야. id는 영문·숫자·밑줄로 만들고 서로 달라야 해. effect에는 '+allowed.join(', ')+' 중 하나만 사용하고 값은 -20~20의 정수로 작성해. description은 효과와 일치해야 해. JSON 외 문장은 제외해. 예: {"id":"juice","name":"회복 주스","description":"체력 10 회복","effect":{"체력":10}}';const promptBox=el('textarea');promptBox.value=promptText;promptBox.readOnly=true;c.appendChild(promptBox);c.appendChild(btn('요청문 선택',()=>{promptBox.focus();promptBox.select();}));
 const work=card(r,'2. 결과를 붙여넣고 검사하세요.'),area=el('textarea');area.placeholder='[ { "id": "juice", ... } ]';work.appendChild(area);let parsed=null;const result=el('pre','아직 검사하지 않았습니다.');
 const add=btn('검사한 항목을 아이템에 추가',()=>{if(!parsed)return;if(!confirm('설명과 실제 효과가 일치하는지 직접 확인했나요? 확인한 항목을 추가합니다.'))return;const existing=new Set(d.items.map(x=>x.id));if(parsed.some(x=>existing.has(x.id)))throw Error('이미 존재하는 ID가 생겼습니다. 다시 검사하세요.');d.items.push(...parsed.map(x=>({...x,icon:''})));b.save();parsed=null;add.disabled=true;result.textContent='아이템에 추가했습니다. 장면 지도에서 선택지의 획득 대상으로 지정하세요.';});add.disabled=true;area.oninput=()=>{parsed=null;add.disabled=true;};
 function check(){parsed=null;add.disabled=true;try{const text=area.value.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');const rows=JSON.parse(text);if(!Array.isArray(rows)||!rows.length||rows.length>100)throw Error('1~100개의 아이템 배열을 입력하세요.');const errors=[],seen=new Set(d.items.map(x=>x.id));rows.forEach((x,i)=>{const tag=(i+1)+'번째';if(!x||typeof x!=='object'||Array.isArray(x)){errors.push(tag+': 객체 필요');return;}if(typeof x.id!=='string'||!/^[A-Za-z0-9_]+$/.test(x.id)||['__proto__','constructor','prototype'].includes(x.id))errors.push(tag+': ID 형식 오류');if(seen.has(x.id))errors.push(tag+': 중복 ID '+x.id);seen.add(x.id);if(typeof x.name!=='string'||!x.name.trim()||typeof x.description!=='string'||!x.description.trim())errors.push(tag+': 이름·설명 필요');if(!x.effect||typeof x.effect!=='object'||Array.isArray(x.effect)||Object.keys(x.effect).length!==1){errors.push(tag+': effect에 스탯 하나가 필요');return;}Object.entries(x.effect).forEach(([k,v])=>{if(!allowed.includes(k))errors.push(tag+': 허용되지 않는 스탯 '+k);if(!Number.isInteger(v)||v< -20||v>20)errors.push(tag+': 효과값은 -20~20 정수');});});if(errors.length){result.textContent=errors.join('\n');return;}parsed=rows.map(x=>({id:x.id,name:x.name,description:x.description,effect:x.effect}));add.disabled=false;result.textContent=rows.length+'개 형식 검사 통과. 다음을 직접 확인하세요.\n\n'+rows.map(x=>x.name+' | 설명: '+x.description+' | 실제: '+JSON.stringify(x.effect)).join('\n')+'\n\n설명과 효과가 일치하는지 확인해야 합니다. 자동 검사는 의미의 정답을 판정하지 않습니다.';}catch(e){result.textContent='읽기/검사 실패: '+e.message;}}
 const errors=[{id:'juice',name:'회복 주스',description:'체력 10 회복',effect:{체력:-10}},{id:'juice',name:'집중 사탕',description:'정신력 10 증가',effect:{정신력:10}},{id:'big',name:'강력 회복',description:'체력 30 증가',effect:{체력:30}},{id:'luck',name:'행운 부적',description:'행운 5 증가',effect:{행운:5}}];
 work.append(btn('검사하기',check,true),btn('연습용 오류 불러오기',()=>{if(area.value&&!confirm('현재 입력을 연습용 오류로 바꿀까요?'))return;area.value=JSON.stringify(errors,null,2);parsed=null;add.disabled=true;result.textContent='오류를 찾아 수정해보세요. 회복 주스의 설명과 부호도 비교하세요.';}),add,result);
 notice(r,'AI 결과가 올바르다면 오류를 억지로 만들 필요는 없습니다. 연습용 오류로 검사 방법을 익혀보세요. 예제 데이터를 수정하며 데이터 형식을 확인할 수 있습니다.');
}
g.Lab={rules,sandbox,ai,choiceExtras};
})(window);
