(function(){
'use strict';
const $=s=>document.querySelector(s),copy=x=>JSON.parse(JSON.stringify(x));
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const button=(text,fn,cls)=>{const n=el('button',text,cls);n.type='button';n.onclick=()=>{try{fn();}catch(e){toast(e.message);}};return n;};
let draft,view='scenes',selected,assetId=null,history=[],last='',zoom=1,toastTimer;
try{draft=JSON.parse(localStorage.getItem('branchStudioDraft')||localStorage.getItem('storyEditorDraft')||'null');}catch(e){}
if(!draft||!draft.scenes)draft=copy(LAB_TEMPLATES.escape);
function normalize(){draft.meta=draft.meta||{};['classes','items','skills','derivedStats','statEndings'].forEach(k=>draft[k]=draft[k]||[]);draft.endings=draft.endings||{};draft.statBounds=draft.statBounds||{};draft.stats=draft.stats||{};draft.meta.layout=draft.meta.layout||{};if(!draft.scenes[selected])selected=draft.startScene||Object.keys(draft.scenes)[0];}
normalize();last=JSON.stringify(draft);
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3800);}
function save(){const next=JSON.stringify(draft);if(next!==last){history.push(last);if(history.length>40)history.shift();last=next;}try{localStorage.setItem('branchStudioDraft',next);$('#saveState').textContent='● 이 기기에 임시 저장됨';}catch(e){$('#saveState').textContent='저장 공간 부족 · 파일로 저장하세요';}chrome();}
function chrome(){$('#projectName').textContent=draft.meta.title||'이름 없는 이야기';$('#projectStats').textContent=Object.keys(draft.scenes).length+' 장면 / '+Object.values(draft.scenes).reduce((n,s)=>n+(s.choices||[]).length,0)+' 선택 / '+Object.keys(draft.endings).length+' 엔딩';$('#undoBtn').disabled=!history.length;}
function field(parent,label,type,value,fn,hint){const wrap=el('label',label,'field');let n;if(type==='textarea'){n=el('textarea');n.value=value||'';}else if(Array.isArray(type)){n=el('select');type.forEach(v=>{const [a,b]=Array.isArray(v)?v:[v,v];const o=el('option',b);o.value=a;n.appendChild(o);});n.value=value??'';}else{n=el('input');n.type=type;n.value=value??'';}n.setAttribute('aria-label',label);n.onchange=()=>{try{fn(type==='number'?Number(n.value):n.value);save();}catch(e){toast(e.message);}};wrap.appendChild(n);if(hint)wrap.appendChild(el('small',hint,'hint'));parent.appendChild(wrap);return n;}
function unique(prefix,pool){let i=1;while(pool.includes(prefix+i))i++;return prefix+i;}
function modal(title,build,play=false){const dialog=$('#studioDialog');if(dialog.open)dialog.close();dialog.className=play?'play-dialog':'';const body=$('#dialogBody');body.replaceChildren();const header=el('div',undefined,'dialog-head');header.append(el('h2',title),button('닫기 ×',()=>dialog.close()));const content=el('div',undefined,'dialog-content');body.append(header,content);build(content);dialog.showModal();}
function download(name,text,type='text/javascript'){const url=URL.createObjectURL(new Blob([text],{type})),a=el('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
function exportData(){download('story-data.js','window.STORY_DATA = '+JSON.stringify(draft,null,2)+';\n');toast('제작 데이터를 내보냈어요. 다운로드 폴더를 확인하세요.');}
function exportPlay(){const r=GameRules.validate(draft);if(r.errors.length){toast('데이터 검사의 오류를 먼저 수정하세요.');return;}const code=s=>s.replace(/<\/script/gi,'<\\/script');const title=(draft.meta.title||'내 이야기').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const html='<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+title+'</title><style>'+RUNTIME_SOURCE.css+'</style><body class="player-body"><main id="app"></main><script>'+code(RUNTIME_SOURCE.rules)+'<\/script><script>'+code(RUNTIME_SOURCE.engine)+'<\/script><script>StoryEngine.init(document.getElementById("app"),'+JSON.stringify(draft).replace(/</g,'\\u003c')+');<\/script></body></html>';download('my-story.html',html,'text/html');toast('플레이 HTML을 저장했어요. 포함한 이미지는 함께 저장됩니다.');}
const bridge={get:()=>draft,save,set:d=>{draft=copy(d);normalize();save();render();},go:v=>{view=v==='sandbox'?'test':v;render();},openAsset:(pool,id,message)=>{view=pool;assetId=id;render();if(message)toast(message);},notify:message=>toast(message),export:exportData};
const nav=[['scenes','⌘','장면 지도'],['items','◇','아이템'],['skills','✦','스킬'],['classes','◉','캐릭터'],['rules','⤴','스탯 연결'],['test','▷','테스트 룸'],['ai','⊞','AI 제작·테스트'],['settings','⚙','프로젝트']];
function render(){normalize();const bar=$('#navigation');bar.replaceChildren();nav.forEach(([id,icon,label])=>{const b=button('',()=>{view=id;assetId=null;render();},view===id?'active':'');b.setAttribute('aria-label',label);b.append(el('span',icon,'nav-icon'),el('span',label));bar.appendChild(b);});const w=$('#workspace');w.replaceChildren();chrome();if(view==='scenes')renderMap();else if(['items','skills','classes'].includes(view))renderAssets();else if(view==='settings')settings();else{const holder=el('div');holder.id='tabContent';holder.style.paddingTop='28px';w.appendChild(holder);({rules:Lab.rules,test:Lab.sandbox,ai:Lab.ai}[view])(bridge);}}
function head(title,sub,actions){const h=el('div',undefined,'page-head'),left=el('div');left.append(el('div','YOUR STORY, YOUR RULES','eyebrow'),el('h1',title),el('p',sub));h.appendChild(left);if(actions)h.appendChild(actions);$('#workspace').appendChild(h);}
function positions(){const layout=draft.meta.layout,keys=Object.keys(draft.scenes),depth={},q=[[draft.startScene,0]];while(q.length){const [k,n]=q.shift();if(depth[k]!==undefined||!draft.scenes[k])continue;depth[k]=n;(draft.scenes[k].choices||[]).forEach(c=>q.push([c.next,n+1]));}const rows={};keys.forEach((k,i)=>{const x=depth[k]??0;const y=rows[x]||0;rows[x]=y+1;if(!layout[k])layout[k]={x:42+x*290,y:42+y*225};});return layout;}
function renderMap(){const actions=el('div');actions.append(button('+ 장면 추가',addScene,'primary'));head('장면을 잇고, 이야기를 만들어요.','카드를 선택하면 오른쪽에서 편집합니다. 카드를 끌어 배치를 바꿀 수 있어요.',actions);const layout=el('div',undefined,'scene-layout'),pane=el('section',undefined,'map-pane'),tools=el('div',undefined,'map-tools');tools.append(el('span','● 시작 장면   ↗ 선택지 연결   ◇ 엔딩'),button('자동 정렬',()=>{draft.meta.layout={};save();renderMapView();}));const z=el('span');z.append(button('−',()=>{zoom=Math.max(.5,zoom-.1);renderMapView();}),el('span',Math.round(zoom*100)+'%'),button('+',()=>{zoom=Math.min(1.3,zoom+.1);renderMapView();}));tools.appendChild(z);pane.appendChild(tools);const scroller=el('div',undefined,'map-scroll');scroller.id='mapScroll';pane.appendChild(scroller);const inspector=el('aside',undefined,'inspector');inspector.id='inspector';layout.append(pane,inspector);$('#workspace').appendChild(layout);drawMap();inspect();}
function renderMapView(){const pos=$('#mapScroll')?[$('#mapScroll').scrollLeft,$('#mapScroll').scrollTop]:[0,0];render();if($('#mapScroll')){$('#mapScroll').scrollLeft=pos[0];$('#mapScroll').scrollTop=pos[1];}}
function drawMap(){const scroller=$('#mapScroll');scroller.replaceChildren();const p=positions(),keys=Object.keys(draft.scenes);const width=Math.max(750,...keys.map(k=>p[k].x+270)),height=Math.max(580,...keys.map(k=>p[k].y+240));const spacer=el('div');spacer.style.width=width*zoom+'px';spacer.style.height=height*zoom+'px';const world=el('div',undefined,'map-world');world.style.width=width+'px';world.style.height=height+'px';world.style.transform='scale('+zoom+')';spacer.appendChild(world);scroller.appendChild(spacer);const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('width',width);svg.setAttribute('height',height);world.appendChild(svg);
 const ns='http://www.w3.org/2000/svg';const defs=document.createElementNS(ns,'defs'),marker=document.createElementNS(ns,'marker');marker.id='arrow';marker.setAttribute('viewBox','0 0 10 10');marker.setAttribute('refX','8');marker.setAttribute('refY','5');marker.setAttribute('markerWidth','5');marker.setAttribute('markerHeight','5');marker.setAttribute('orient','auto-start-reverse');const arrow=document.createElementNS(ns,'path');arrow.setAttribute('d','M 0 0 L 10 5 L 0 10 z');arrow.setAttribute('fill','#8aab7c');marker.appendChild(arrow);defs.appendChild(marker);svg.appendChild(defs);
 keys.forEach(k=>(draft.scenes[k].choices||[]).forEach((c,i)=>{if(!p[c.next]||!draft.scenes[c.next])return;const a=p[k],b=p[c.next],line=document.createElementNS(ns,'path');let path;if(k===c.next)path=`M ${a.x+180} ${a.y+150} C ${a.x+290} ${a.y+250}, ${a.x-50} ${a.y+250}, ${a.x+30} ${a.y+166}`;else if(b.x>a.x)path=`M ${a.x+222} ${a.y+85} C ${a.x+267} ${a.y+85}, ${b.x-45} ${b.y+85}, ${b.x} ${b.y+85}`;else path=`M ${a.x+110} ${a.y+166} C ${a.x+110} ${a.y+205+i*12}, ${b.x+110} ${b.y+205+i*12}, ${b.x+110} ${b.y+166}`;line.setAttribute('d',path);line.setAttribute('fill','none');line.setAttribute('stroke',k===selected?'#387e5c':'#a9bda0');line.setAttribute('stroke-width',k===selected?'2':'1.3');line.setAttribute('marker-end','url(#arrow)');svg.appendChild(line);}));
 keys.forEach((k,i)=>{const s=draft.scenes[k],end=Object.values(draft.endings).find(e=>e.sceneId===k),n=el('button',undefined,'map-node'+(k===selected?' active':'')+(end?' ending':''));n.type='button';n.setAttribute('aria-label','장면 '+(s.title||k));n.style.left=p[k].x+'px';n.style.top=p[k].y+'px';const top=el('div',undefined,'node-top');top.append(el('span',String(i+1).padStart(2,'0')+' / '+k),el('span',end?'◇ END':k===draft.startScene?'● START':'SCENE','type'));const body=el('div',undefined,'node-body');body.append(el('h3',s.title||end?.title||k),el('p',s.text||'아직 쓰지 않은 이야기'));const foot=el('div',undefined,'node-foot');foot.append(el('span',end?'엔딩':(s.choices||[]).length+'개의 선택'),el('span',s.image?'이미지 있음':'↗'));n.append(top,body,foot);world.appendChild(n);
 let drag=null,moved=false;n.onpointerdown=e=>{if(e.button!==0)return;drag={x:e.clientX,y:e.clientY,ox:p[k].x,oy:p[k].y};moved=false;n.setPointerCapture(e.pointerId);};n.onpointermove=e=>{if(!drag)return;const dx=(e.clientX-drag.x)/zoom,dy=(e.clientY-drag.y)/zoom;if(Math.abs(dx)+Math.abs(dy)>4)moved=true;if(moved){n.style.left=Math.max(12,drag.ox+dx)+'px';n.style.top=Math.max(12,drag.oy+dy)+'px';}};n.onpointerup=()=>{if(!drag)return;if(moved){p[k]={x:parseFloat(n.style.left),y:parseFloat(n.style.top)};save();}drag=null;selected=k;drawMap();inspect();};n.onclick=e=>{if(e.detail===0){selected=k;drawMap();inspect();}};
 });}
function addScene(){const id=unique('scene_',Object.keys(draft.scenes));draft.scenes[id]={title:'새로운 장면',text:'여기서 어떤 일이 일어날까요?',image:'',choices:[]};selected=id;save();renderMapView();}
function mediaField(parent,s){const box=el('div',undefined,'media-drop'),file=el('input');file.type='file';file.accept='image/png,image/jpeg,image/webp,image/gif';file.hidden=true;function load(f){if(!f)return;if(!/^image\/(png|jpeg|webp|gif)$/.test(f.type)){toast('PNG, JPG, WebP, GIF 이미지를 선택하세요.');return;}if(f.size>4*1024*1024){toast('4MB 이하 이미지를 사용하세요.');return;}const reader=new FileReader();reader.onload=()=>{s.image=reader.result;save();inspect();drawMap();};reader.readAsDataURL(f);}if(s.image){const img=el('img');img.src=/^data:image\//.test(s.image)?s.image:'images/'+s.image;img.onerror=()=>img.remove();box.appendChild(img);}box.append(el('span','이미지를 끌어놓거나 클릭해서 포함하기'),file);box.tabIndex=0;box.setAttribute('role','button');box.setAttribute('aria-label','장면 이미지 추가');box.onclick=()=>file.click();box.onkeydown=e=>{if(e.key==='Enter')file.click();};file.onclick=e=>e.stopPropagation();file.onchange=()=>load(file.files[0]);box.ondragover=e=>{e.preventDefault();box.classList.add('dragover');};box.ondragleave=()=>box.classList.remove('dragover');box.ondrop=e=>{e.preventDefault();box.classList.remove('dragover');load(e.dataTransfer.files[0]);};parent.appendChild(box);if(s.image)parent.appendChild(button('이미지 제거',()=>{s.image='';save();inspect();drawMap();},'quiet'));}
function kv(parent,obj,label){const wrap=el('div');parent.appendChild(wrap);function paint(){wrap.replaceChildren();Object.entries(obj).forEach(([k,v])=>{const row=el('div',undefined,'split-fields');field(row,k,'number',v,n=>obj[k]=n);row.appendChild(button('삭제',()=>{delete obj[k];save();paint();},'quiet'));wrap.appendChild(row);});wrap.appendChild(button('+ '+label,()=>{const keys=Object.keys(draft.stats).filter(k=>!Object.hasOwn(obj,k));if(!keys.length){toast('추가할 스탯이 없어요. 스탯 연결에서 먼저 만드세요.');return;}modal(label,body=>{let key=keys[0];field(body,'스탯',keys,key,v=>key=v);body.appendChild(button('추가',()=>{obj[key]=0;save();$('#studioDialog').close();paint();},'primary'));});}));}paint();}
function inspect(){const panel=$('#inspector');if(!panel)return;panel.replaceChildren();const s=draft.scenes[selected];if(!s){panel.appendChild(el('p','장면을 선택하세요.'));return;}panel.append(el('div','SCENE INSPECTOR','inspector-label'),el('h2',s.title||selected));field(panel,'장면 제목','text',s.title||selected,v=>{s.title=v;drawMap();});field(panel,'이야기','textarea',s.text,v=>{s.text=v;drawMap();});mediaField(panel,s);const mediaMore=el('details');mediaMore.appendChild(el('summary','파일명으로 이미지·영상 연결'));field(mediaMore,'이미지 파일명','text',s.image?.startsWith('data:')?'':s.image||'',v=>s.image=v,'images 폴더의 파일명. 입력하면 포함된 이미지를 교체합니다.');field(mediaMore,'영상 파일명','text',s.video||'',v=>s.video=v||null,'videos 폴더에 직접 복사하세요.');panel.appendChild(mediaMore);
 const endEntry=Object.entries(draft.endings).find(([,x])=>x.sceneId===selected);field(panel,'장면 유형',[['scene','일반 장면'],['ending','엔딩']],endEntry?'ending':'scene',v=>{if(v==='ending'){if(s.choices.length&&!confirm('엔딩에서는 선택지가 실행되지 않습니다. 엔딩으로 설정할까요?'))return;const id=unique('ending_',Object.keys(draft.endings));draft.endings[id]={sceneId:selected,title:s.title||'새 엔딩'};}else if(endEntry){const referenced=draft.statEndings.some(r=>r.endingId===endEntry[0]);if(referenced){toast('프로젝트의 자동 엔딩 규칙을 먼저 삭제하세요.');inspect();return;}delete draft.endings[endEntry[0]];}save();inspect();drawMap();});if(endEntry)field(panel,'엔딩 제목','text',endEntry[1].title,v=>{endEntry[1].title=v;drawMap();});
 const section=el('div',undefined,'section-label');section.append(el('span','선택지 '+s.choices.length),button('+ 추가',()=>{s.choices.push({label:'새로운 선택',next:selected,effects:{}});save();inspect();drawMap();}));panel.appendChild(section);
 s.choices.forEach((c,i)=>{const card=el('div',undefined,'choice-card'),top=el('div',undefined,'choice-no');top.append(el('span','CHOICE '+String(i+1).padStart(2,'0')),button('×',()=>{s.choices.splice(i,1);save();inspect();drawMap();}));card.appendChild(top);field(card,'선택 '+(i+1)+' 문구','text',c.label,v=>c.label=v);field(card,'선택 '+(i+1)+' 다음 장면',Object.entries(draft.scenes).map(([k,x])=>[k,x.title||k]),c.next,v=>{c.next=v;drawMap();});const advanced=el('details');advanced.appendChild(el('summary','조건 · 효과 · 획득'));card.appendChild(advanced);
 // Flatten imported requirements so every condition is visible and editable.
 if(c.requires){c.requiresAll=c.requiresAll||[];Object.entries(c.requires).forEach(([k,v])=>{if(k==='statAtLeast')Object.entries(v).forEach(([stat,n])=>c.requiresAll.push({statAtLeast:{[stat]:n}}));else c.requiresAll.push({[k]:v});});c.requires=null;save();}
 c.effects=c.effects||{};kv(advanced,c.effects,'스탯 효과');[['grantItem','items','획득 아이템'],['grantSkill','skills','획득 스킬']].forEach(([key,pool,label])=>{const random=typeof c[key]==='object'&&!Array.isArray(c[key])&&c[key]?.random;if(random){advanced.appendChild(el('p',label+' 랜덤: '+random.join(', ')));advanced.appendChild(button('랜덤 지급 해제',()=>{c[key]=null;save();inspect();}));}else field(advanced,label,[['','없음'],...draft[pool].map(x=>[x.id,x.name])],typeof c[key]==='string'?c[key]:'',v=>c[key]=v||null);const poolbox=el('details');poolbox.appendChild(el('summary',label+' 랜덤 선택'));const picked=new Set(random||[]);draft[pool].forEach(it=>{const l=el('label',undefined,'field'),cb=el('input');cb.type='checkbox';cb.checked=picked.has(it.id);cb.onchange=()=>cb.checked?picked.add(it.id):picked.delete(it.id);l.append(cb,el('span',it.name));poolbox.appendChild(l);});poolbox.appendChild(button('랜덤 지급 적용',()=>{c[key]=picked.size?{random:[...picked]}:null;save();inspect();}));advanced.appendChild(poolbox);});Lab.choiceExtras(advanced,c,bridge);panel.appendChild(card);});
 const actions=el('div',undefined,'form-actions');actions.append(button('여기서 테스트',()=>{view='test';render();const n=$('#tabContent select[aria-label="시작 장면"]');if(n)n.value=selected;toast('시작 상태를 정하고 실행하세요.');}),button('시작 장면으로',()=>{draft.startScene=selected;save();drawMap();}),button('복제',()=>{const id=unique(selected+'_',Object.keys(draft.scenes));draft.scenes[id]=copy(s);draft.scenes[id].title=(s.title||selected)+' 사본';selected=id;save();renderMapView();}),button('삭제',()=>{if(Object.keys(draft.scenes).length===1){toast('장면은 하나 이상 있어야 합니다.');return;}const refs=Object.entries(draft.scenes).filter(([k,x])=>k!==selected&&x.choices.some(c=>c.next===selected));if(refs.length||endEntry||selected===draft.startScene){toast('시작·엔딩 지정과 다른 장면의 연결을 먼저 해제하세요.');return;}if(!confirm('이 장면을 삭제할까요?'))return;delete draft.scenes[selected];delete draft.meta.layout[selected];selected=Object.keys(draft.scenes)[0];save();renderMapView();},'danger'));panel.appendChild(actions);
}
function renderAssets(){const pool=draft[view],name={items:'아이템',skills:'스킬',classes:'캐릭터'}[view],actions=button('+ '+name+' 추가',()=>{const id=unique(view.slice(0,-1)+'_',pool.map(x=>x.id));pool.push({id,name:'새 '+name,...(view==='items'?{effect:{}}:view==='classes'?{startingStats:{},description:''}:{requires:null})});assetId=id;save();render();},'primary');head(name+' 라이브러리','이야기 속에 등장할 '+name+'와 규칙을 관리해요.',actions);const main=el('div',undefined,'content-page'),layout=el('div',undefined,'asset-layout'),list=el('div',undefined,'asset-list'),detail=el('section',undefined,'asset-detail');if(!pool.some(x=>x.id===assetId))assetId=pool[0]?.id;pool.forEach(x=>{const b=button('',()=>{assetId=x.id;render();},'asset-card'+(assetId===x.id?' active':'')),text=el('div');text.append(el('strong',x.name),el('small',x.id));b.append(el('span',view==='items'?'◇':view==='skills'?'✦':'◉','asset-symbol'),text);list.appendChild(b);});const x=pool.find(x=>x.id===assetId);if(!x)detail.appendChild(el('p','새 '+name+'를 추가해보세요.','empty'));else{detail.append(el('div',x.id,'eyebrow'),el('h2',x.name));field(detail,'이름','text',x.name,v=>{x.name=v;render();});field(detail,'설명','textarea',x.description||'',v=>x.description=v);if(view==='items'){detail.appendChild(el('p','처음 획득할 때 한 번 적용되는 효과예요.','muted'));x.effect=x.effect||{};kv(detail,x.effect,'획득 효과');field(detail,'아이콘 파일명','text',x.icon||'',v=>x.icon=v,'images 폴더의 파일명');}if(view==='classes'){x.startingStats=x.startingStats||{};detail.appendChild(el('p','기본 시작값을 이 캐릭터의 값으로 바꿉니다.','muted'));kv(detail,x.startingStats,'시작 스탯');}if(view==='skills'){field(detail,'획득 가능한 캐릭터',[['','모두'],...draft.classes.map(c=>[c.id,c.name])],x.requires?.class||'',v=>{x.requires={...(x.requires||{})};if(v)x.requires.class=v;else delete x.requires.class;});}detail.appendChild(button(name+' 삭제',()=>{const text=JSON.stringify(draft.scenes);if(text.includes('"'+x.id+'"')){toast('장면의 조건 또는 지급에서 사용 중입니다. 연결을 먼저 해제하세요.');return;}if(view==='classes'&&draft.skills.some(s=>s.requires?.class===x.id)){toast('스킬의 캐릭터 조건을 먼저 해제하세요.');return;}if(confirm(name+'를 삭제할까요?')){pool.splice(pool.indexOf(x),1);assetId=null;save();render();}},'danger'));}layout.append(list,detail);main.appendChild(layout);$('#workspace').appendChild(main);}
function settings(){head('이야기의 첫인상을 정해요.','제목, 분위기, 시작점과 엔딩 규칙을 한곳에서 관리합니다.');const main=el('div',undefined,'content-page'),grid=el('div',undefined,'settings-grid'),card=el('section',undefined,'card');card.appendChild(el('h2','표지와 분위기'));field(card,'게임 제목','text',draft.meta.title,v=>draft.meta.title=v);field(card,'한 줄 소개','textarea',draft.meta.tagline||'',v=>draft.meta.tagline=v);field(card,'만든 사람','text',draft.meta.author||'',v=>draft.meta.author=v);field(card,'분위기',[['forest','심야의 초록'],['amber','황혼의 금빛'],['violet','보랏빛 미지']],draft.meta.theme||'forest',v=>draft.meta.theme=v);field(card,'시작 장면',Object.entries(draft.scenes).map(([k,s])=>[k,s.title||k]),draft.startScene,v=>draft.startScene=v);const end=el('section',undefined,'card');end.append(el('h2','자동 엔딩'),el('p','위에서부터 확인하고, 먼저 맞는 엔딩으로 이동합니다.'));draft.statEndings.forEach((r,i)=>{const box=el('div',undefined,'choice-card');field(box,'규칙 '+(i+1)+' 스탯',Object.keys(draft.stats),r.stat,v=>r.stat=v);const row=el('div',undefined,'split-fields');field(row,'비교',[['lte','이하'],['lt','미만'],['gte','이상'],['gt','초과'],['eq','같음']],r.op,v=>r.op=v);field(row,'기준값','number',r.value,v=>r.value=v);box.appendChild(row);field(box,'엔딩',Object.entries(draft.endings).map(([id,x])=>[id,x.title]),r.endingId,v=>r.endingId=v);box.append(button('↑',()=>{if(i){[draft.statEndings[i-1],draft.statEndings[i]]=[r,draft.statEndings[i-1]];save();render();}}),button('규칙 삭제',()=>{draft.statEndings.splice(i,1);save();render();},'danger'));end.appendChild(box);});end.appendChild(button('+ 엔딩 규칙',()=>{if(!Object.keys(draft.endings).length){toast('장면 지도에서 엔딩을 먼저 만드세요.');return;}draft.statEndings.push({stat:Object.keys(draft.stats)[0],op:'lte',value:0,endingId:Object.keys(draft.endings)[0]});save();render();}));grid.append(card,end);main.appendChild(grid);const actions=el('div',undefined,'form-actions');actions.append(button('새 프로젝트',templates),button('데이터 검사',validate),button('고급 JSON 편집',jsonEditor));main.appendChild(actions);$('#workspace').appendChild(main);}
function templates(){modal('어떤 이야기를 만들까요?',body=>{const grid=el('div',undefined,'template-grid');[['escape','문 너머의 이야기','갈림길, 아이템과 숨겨진 선택. 탈출형 이야기에서 출발해요.','↗'],['battle','선택하는 전투','공격 선택과 아이템 효과로 수치가 변하는 전투 이야기예요.','◇']].forEach(([id,title,desc,symbol])=>{const b=button('',()=>{if(!confirm('현재 작업을 새 프로젝트로 바꿀까요? 보관하려면 먼저 파일로 저장하세요.'))return;draft=copy(LAB_TEMPLATES[id]);selected=draft.startScene;save();view='scenes';$('#studioDialog').close();render();},'template-choice');b.append(el('div',symbol,'template-art'),el('strong',title),el('small',desc));grid.appendChild(b);});body.appendChild(grid);});}
function validate(){modal('데이터 검사',body=>{const r=GameRules.validate(draft);body.append(el('h3',r.errors.length?'확인할 오류 '+r.errors.length+'개':'연결과 데이터 형식이 정상이에요.'),el('pre',r.errors.concat(r.warnings).join('\n')||'이제 테스트 룸에서 서로 다른 상태로 실행해보세요.'));});}
function jsonEditor(){modal('고급 JSON 편집',body=>{const a=el('textarea');a.value=JSON.stringify(draft,null,2);a.setAttribute('aria-label','게임 JSON');body.append(a,button('적용',()=>{let d=JSON.parse(a.value);const r=GameRules.validate(d);if(r.errors.length)throw Error(r.errors.join('\n'));draft=d;normalize();save();$('#studioDialog').close();render();},'primary'));});}
$('#playBtn').onclick=()=>modal('플레이 미리보기',body=>StoryEngine.init(body,draft),true);
$('#saveBtn').onclick=()=>modal('내 이야기 저장하기',body=>{body.classList.add('save-menu');const a=button('제작 데이터 저장',exportData);a.appendChild(el('small','story-data.js · 다음에 불러와서 계속 편집'));const b=button('플레이 HTML 저장',exportPlay);b.appendChild(el('small','my-story.html · 에디터 없이 바로 실행. 포함 이미지도 함께 저장'));body.append(a,b,el('p','파일명으로 연결한 외부 이미지·영상은 images / videos 폴더도 함께 옮겨주세요.','muted'));});
$('#undoBtn').onclick=()=>{if(!history.length)return;draft=JSON.parse(history.pop());normalize();last=JSON.stringify(draft);try{localStorage.setItem('branchStudioDraft',last);}catch(e){}render();toast('이전 변경으로 돌아왔어요.');};
$('#importBtn').onclick=()=>$('#importFile').click();$('#importFile').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const txt=String(reader.result).trim(),m=txt.match(/window\.STORY_DATA\s*=\s*(\{[\s\S]*\})\s*;?\s*$/),d=JSON.parse(m?m[1]:txt),r=GameRules.validate(d);if(r.errors.length)throw Error(r.errors.join('\n'));draft=d;selected=d.startScene;normalize();save();render();toast('이야기를 불러왔어요.');}catch(err){toast('프로젝트 불러오기 실패: '+err.message);}};reader.readAsText(file);e.target.value='';};
render();
})();
